/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module udcounter(clk, rst, up_dn, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input up_dn;
  wire up_dn;
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  sky130_fd_sc_hd__inv_2 _16_ (
    .A(count[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2_2 _17_ (
    .A(count[0]),
    .B(rst),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_2 _18_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__or2_2 _19_ (
    .A(count[1]),
    .B(count[0]),
    .X(_06_)
  );
  sky130_fd_sc_hd__a21o_2 _20_ (
    .A1(_05_),
    .A2(_06_),
    .B1(up_dn),
    .X(_07_)
  );
  sky130_fd_sc_hd__nand3_2 _21_ (
    .A(up_dn),
    .B(_05_),
    .C(_06_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_2 _22_ (
    .A1(_07_),
    .A2(_08_),
    .B1(rst),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_2 _23_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .X(_09_)
  );
  sky130_fd_sc_hd__a21oi_2 _24_ (
    .A1(count[1]),
    .A2(count[0]),
    .B1(count[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__or2_2 _25_ (
    .A(_09_),
    .B(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__a21oi_2 _26_ (
    .A1(_07_),
    .A2(_11_),
    .B1(rst),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o21a_2 _27_ (
    .A1(_07_),
    .A2(_11_),
    .B1(_12_),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor3_2 _28_ (
    .A(count[1]),
    .B(count[0]),
    .C(up_dn),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o22a_2 _29_ (
    .A1(_04_),
    .A2(up_dn),
    .B1(_09_),
    .B2(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__a21oi_2 _30_ (
    .A1(count[3]),
    .A2(_14_),
    .B1(rst),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21a_2 _31_ (
    .A1(count[3]),
    .A2(_14_),
    .B1(_15_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_2 _32_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _33_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _34_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _35_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule
