/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "mux4_using_mux2.v:1.1-19.10" *)
module mux4(d0, d1, d2, d3, sel, y);
  (* src = "mux4_using_mux2.v:2.17-2.19" *)
  input d0;
  wire d0;
  (* src = "mux4_using_mux2.v:3.17-3.19" *)
  input d1;
  wire d1;
  (* src = "mux4_using_mux2.v:4.17-4.19" *)
  input d2;
  wire d2;
  (* src = "mux4_using_mux2.v:5.17-5.19" *)
  input d3;
  wire d3;
  (* src = "mux4_using_mux2.v:6.23-6.26" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "mux4_using_mux2.v:7.17-7.18" *)
  output y;
  wire y;
  (* hdlname = "m0 a" *)
  (* src = "mux2.v:2.17-2.18" *)
  wire \m0.a ;
  (* hdlname = "m0 b" *)
  (* src = "mux2.v:3.17-3.18" *)
  wire \m0.b ;
  (* hdlname = "m0 sel" *)
  (* src = "mux2.v:4.17-4.20" *)
  wire \m0.sel ;
  (* hdlname = "m0 y" *)
  (* src = "mux2.v:5.17-5.18" *)
  wire \m0.y ;
  (* hdlname = "m1 a" *)
  (* src = "mux2.v:2.17-2.18" *)
  wire \m1.a ;
  (* hdlname = "m1 b" *)
  (* src = "mux2.v:3.17-3.18" *)
  wire \m1.b ;
  (* hdlname = "m1 sel" *)
  (* src = "mux2.v:4.17-4.20" *)
  wire \m1.sel ;
  (* hdlname = "m1 y" *)
  (* src = "mux2.v:5.17-5.18" *)
  wire \m1.y ;
  (* hdlname = "m2 a" *)
  (* src = "mux2.v:2.17-2.18" *)
  wire \m2.a ;
  (* hdlname = "m2 b" *)
  (* src = "mux2.v:3.17-3.18" *)
  wire \m2.b ;
  (* hdlname = "m2 sel" *)
  (* src = "mux2.v:4.17-4.20" *)
  wire \m2.sel ;
  (* hdlname = "m2 y" *)
  (* src = "mux2.v:5.17-5.18" *)
  wire \m2.y ;
  (* src = "mux4_using_mux2.v:10.10-10.12" *)
  wire y0;
  (* src = "mux4_using_mux2.v:10.14-10.16" *)
  wire y1;
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _0_ (
    .I0(d0),
    .I1(d1),
    .S(sel[0]),
    .Z(\m0.y )
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _1_ (
    .I0(d2),
    .I1(d3),
    .S(sel[0]),
    .Z(\m1.y )
  );
  gf180mcu_fd_sc_mcu9t5v0__mux2_1 _2_ (
    .I0(\m0.y ),
    .I1(\m1.y ),
    .S(sel[1]),
    .Z(y)
  );
  assign \m0.a  = d0;
  assign \m0.b  = d1;
  assign \m0.sel  = sel[0];
  assign \m1.a  = d2;
  assign \m1.b  = d3;
  assign \m1.sel  = sel[0];
  assign \m2.a  = \m0.y ;
  assign \m2.b  = \m1.y ;
  assign \m2.sel  = sel[1];
  assign \m2.y  = y;
  assign y0 = \m0.y ;
  assign y1 = \m1.y ;
endmodule
